"""Generate PWA icon assets for BookWorm.

Produces PNG files inside static/img/icons/:
  icon-192.png          — standard 192×192
  icon-512.png          — standard 512×512
  icon-maskable-512.png — 512×512 (Android adaptive safe-zone)
  apple-touch-icon.png  — 180×180 (iOS Add-to-Home-Screen)
  badge-96.png          — 96×96 white-on-transparent monochrome push badge

NOTE: the home-page widget *shortcut* icons (shortcut-*.png) are generated by
bw_shortcut_icons.py and are intentionally left untouched by this module.

Files are only written when missing; call generate_icons(force=True) to redraw.

Design: a cute green caterpillar — segmented body with little feet, a friendly
two-eyed face + smile, and antennae — on a deep-green background that matches the
PWA splash/page colour (#1b4332). Matching means the splash reads as one solid
colour with the caterpillar floating on it (no visible circle edge), and the
background green is intentionally darker than the caterpillar's body greens.
The amber-worm-on-blue design that this replaced is preserved below as the
unused `_make_worm_icon()` for reference.
"""
import math
import os

from PIL import Image, ImageDraw, ImageFilter

# ── Palette (caterpillar) ────────────────────────────────────────────────────
# Background = the PWA page/splash colour so the icon's circle blends into the
# loading screen. Deliberately darker than the caterpillar's body greens.
_BG_DARK  = ( 27,  67,  50)   # deep green = #1b4332 (matches manifest bg/theme)
_MINT_TOP = (236, 253, 245)   # mint-50   #ecfdf5  (kept for the preserved worm)
_MINT_BOT = (167, 243, 208)   # emerald-200 #a7f3d0
_GREEN    = ( 34, 163,  74)   # leaf green        #22a34a
_GREEN_HD = ( 52, 199,  89)   # brighter head     #34c759
_GREEN_HI = (134, 239, 172)   # highlight         #86efac
_GREEN_DK = ( 20,  83,  45)   # dark border/legs  #14532d
_WHITE    = (255, 255, 255)
_INK      = ( 22,  30,  24)
_CHEEK    = (244, 114, 100, 95)   # RGBA soft blush

_OUT_DIR = os.path.join(os.path.dirname(__file__), "static", "img", "icons")

# (filename, size, full_bleed) — full_bleed is retained for signature
# compatibility; with a transparent background it has no visual effect.
_SPECS = [
    ("icon-192.png",          192, False),
    ("icon-512.png",          512, False),
    ("icon-maskable-512.png", 512, True),
    ("apple-touch-icon.png",  180, True),
]

# Caterpillar segments as fractions of the icon size: (cx, cy, r), tail → head.
_SEGS = [
    (0.215, 0.605, 0.088),
    (0.340, 0.585, 0.104),
    (0.468, 0.560, 0.112),
    (0.595, 0.520, 0.116),
]
_HEAD = (0.730, 0.452, 0.150)   # brighter, largest


def _gradient_square(s: int, top: tuple, bottom: tuple) -> Image.Image:
    """Vertical top→bottom gradient, RGBA, fully opaque. (Used by the preserved
    worm design; the caterpillar draws on a transparent background.)"""
    img = Image.new("RGB", (s, s))
    d = ImageDraw.Draw(img)
    for y in range(s):
        t = y / max(1, s - 1)
        d.line([(0, y), (s, y)], fill=tuple(
            int(top[i] * (1 - t) + bottom[i] * t) for i in range(3)))
    return img.convert("RGBA")


def _disc(d, cx, cy, r, fill):
    d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=fill)


def _make_icon(size: int, full_bleed: bool = False) -> Image.Image:
    """The active app icon: a green caterpillar on a deep-green background that
    matches the PWA page/splash colour (#1b4332) — flat so the splash reads as a
    single colour with the caterpillar floating on it."""
    s = size
    base = Image.new("RGBA", (s, s), (*_BG_DARK, 255))
    if not full_bleed:
        # rounded square (standard icons); maskable/apple-touch stay full-bleed
        mask = Image.new("L", (s, s), 0)
        ImageDraw.Draw(mask).rounded_rectangle(
            [0, 0, s - 1, s - 1], radius=int(s * 0.225), fill=255)
        rounded = Image.new("RGBA", (s, s), (0, 0, 0, 0))
        rounded.paste(base, (0, 0), mask)
        base = rounded

    segs = [(cx * s, cy * s, r * s) for (cx, cy, r) in _SEGS]
    hx, hy, hr = (_HEAD[0] * s, _HEAD[1] * s, _HEAD[2] * s)
    bd = max(2.0, s * 0.013)   # dark border thickness

    # ── Soft drop shadow (depth over whatever sits behind the icon) ──────────
    sh = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    sd = ImageDraw.Draw(sh)
    for (cx, cy, r) in segs + [(hx, hy, hr)]:
        sd.ellipse([cx - r, cy - r + s * 0.02, cx + r, cy + r + s * 0.02],
                   fill=(0, 0, 0, 55))
    base = Image.alpha_composite(base, sh.filter(ImageFilter.GaussianBlur(int(s * 0.02))))
    d = ImageDraw.Draw(base)

    # ── Little feet (under each body segment) ────────────────────────────────
    for (cx, cy, r) in segs:
        fy = cy + r * 0.78
        fw, fh = r * 0.30, r * 0.42
        for fx in (cx - r * 0.42, cx + r * 0.42):
            d.ellipse([fx - fw, fy - fh, fx + fw, fy + fh + r * 0.25], fill=_GREEN_DK)

    # ── Body segments: dark border, fill, highlight ──────────────────────────
    for (cx, cy, r) in segs:
        _disc(d, cx, cy, r + bd, _GREEN_DK)
        _disc(d, cx, cy, r, _GREEN)
    _disc(d, hx, hy, hr + bd, _GREEN_DK)
    _disc(d, hx, hy, hr, _GREEN_HD)

    hi = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    hd = ImageDraw.Draw(hi)
    for (cx, cy, r) in segs:
        hrr = r * 0.52
        hd.ellipse([cx - r * 0.62, cy - r * 0.66, cx - r * 0.62 + hrr, cy - r * 0.66 + hrr],
                   fill=(*_GREEN_HI, 150))
    hd.ellipse([hx - hr * 0.58, hy - hr * 0.62, hx - hr * 0.58 + hr * 0.5,
                hy - hr * 0.62 + hr * 0.5], fill=(*_GREEN_HI, 150))
    base = Image.alpha_composite(base, hi.filter(ImageFilter.GaussianBlur(int(s * 0.008))))
    d = ImageDraw.Draw(base)

    # ── Antennae ─────────────────────────────────────────────────────────────
    aw = max(2, int(s * 0.016))
    atr = max(3, int(s * 0.028))
    for sgn, lean in ((-1, 0.55), (1, 0.62)):
        bx, by = hx + sgn * hr * 0.34, hy - hr * 0.78
        tx, ty = bx + sgn * hr * 0.40, by - hr * lean
        d.line([(bx, by), (tx, ty)], fill=_GREEN_DK, width=aw)
        _disc(d, tx, ty, atr, _GREEN_HD)

    # ── Rosy cheeks ──────────────────────────────────────────────────────────
    ck = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    cd = ImageDraw.Draw(ck)
    ckr = hr * 0.26
    for sgn in (-1, 1):
        cd.ellipse([hx + sgn * hr * 0.64 - ckr, hy + hr * 0.30 - ckr,
                    hx + sgn * hr * 0.64 + ckr, hy + hr * 0.30 + ckr], fill=_CHEEK)
    base = Image.alpha_composite(base, ck)
    d = ImageDraw.Draw(base)

    # ── Eyes + smile ─────────────────────────────────────────────────────────
    er, eoff, ey = hr * 0.30, hr * 0.40, hy - hr * 0.10
    for ex in (hx - eoff, hx + eoff):
        _disc(d, ex, ey, er, _WHITE)
        pr = er * 0.56
        pcx, pcy = ex + er * 0.08, ey + er * 0.10
        _disc(d, pcx, pcy, pr, _INK)
        cr = max(1, er * 0.24)
        _disc(d, pcx - pr * 0.5, pcy - pr * 0.5, cr, _WHITE)
    sm = hr * 0.44
    smt = ey + hr * 0.34
    d.arc([hx - sm, smt, hx + sm, smt + sm * 0.95],
          start=18, end=162, fill=_INK, width=max(2, int(s * 0.017)))

    return base


def _make_badge(size: int = 96) -> Image.Image:
    """White caterpillar silhouette on transparent (Android push badge)."""
    s = size
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    for (cx, cy, r) in _SEGS:
        _disc(d, cx * s, cy * s, r * s, (255, 255, 255, 255))
    _disc(d, _HEAD[0] * s, _HEAD[1] * s, _HEAD[2] * s, (255, 255, 255, 255))
    return img


def generate_icons(out_dir: str = _OUT_DIR, force: bool = False) -> None:
    """Write PNG icons to *out_dir*. Skips existing files unless *force=True*."""
    os.makedirs(out_dir, exist_ok=True)
    for name, size, full_bleed in _SPECS:
        path = os.path.join(out_dir, name)
        if not force and os.path.exists(path):
            continue
        _make_icon(size, full_bleed).save(path, "PNG", optimize=True)
    badge_path = os.path.join(out_dir, "badge-96.png")
    if force or not os.path.exists(badge_path):
        _make_badge(96).save(badge_path, "PNG", optimize=True)


# ══════════════════════════════════════════════════════════════════════════════
# PRESERVED (NOT USED) — the previous app icon: a chunky amber worm with a
# friendly face on a blue gradient. Kept for reference / easy revival. To use it
# as the app icon again, call `_make_worm_icon(size, full_bleed)` from
# generate_icons() in place of `_make_icon`.
# ══════════════════════════════════════════════════════════════════════════════
_WORM_BG_TOP  = ( 56, 116, 240)   # bright brand blue   #3874f0
_WORM_BG_BOT  = ( 12,  42, 122)   # deep indigo         #0c2a7a
_WORM_YELLOW  = (251, 191,  36)   # warm amber          #fbbf24
_WORM_HI      = (254, 222, 130)   # amber highlight     #fede82
_WORM_DARK    = (180,  83,   9)   # amber shadow/border #b45309


def _worm_path(s: int):
    """Sample points (x, y, r) along the worm body, tail→head."""
    pts = []
    N = 240
    for i in range(N + 1):
        t = i / N
        x = 0.165 + 0.600 * t
        y = 0.580 - 0.090 * math.sin(t * math.pi * 1.85) - 0.090 * t
        r = 0.082 + 0.048 * (t ** 0.7)
        pts.append((x * s, y * s, r * s))
    return pts


def _make_worm_icon(size: int, full_bleed: bool = False) -> Image.Image:
    """PRESERVED previous design: amber worm on a blue gradient (not currently used)."""
    s = size
    base = _gradient_square(s, _WORM_BG_TOP, _WORM_BG_BOT)
    if not full_bleed:
        mask = Image.new("L", (s, s), 0)
        ImageDraw.Draw(mask).rounded_rectangle([0, 0, s - 1, s - 1], radius=int(s * 0.225), fill=255)
        rounded = Image.new("RGBA", (s, s), (0, 0, 0, 0))
        rounded.paste(base, (0, 0), mask)
        base = rounded

    pts = _worm_path(s)
    sh = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    sd = ImageDraw.Draw(sh)
    for (x, y, r) in pts[::3]:
        sd.ellipse([x - r, y - r + s * 0.018, x + r, y + r + s * 0.018], fill=(0, 0, 0, 70))
    base = Image.alpha_composite(base, sh.filter(ImageFilter.GaussianBlur(int(s * 0.02))))
    d = ImageDraw.Draw(base)

    for (x, y, r) in pts:
        bdw = r + max(1.5, s * 0.012)
        d.ellipse([x - bdw, y - bdw, x + bdw, y + bdw], fill=_WORM_DARK)
    for (x, y, r) in pts:
        d.ellipse([x - r, y - r, x + r, y + r], fill=_WORM_YELLOW)

    hi = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    hd = ImageDraw.Draw(hi)
    for (x, y, r) in pts[14:-6]:
        hr2 = r * 0.34
        cy = y - r * 0.48
        hd.ellipse([x - hr2, cy - hr2, x + hr2, cy + hr2], fill=(*_WORM_HI, 105))
    base = Image.alpha_composite(base, hi.filter(ImageFilter.GaussianBlur(int(s * 0.014))))
    d = ImageDraw.Draw(base)

    hx, hy, hr = pts[-1]
    ck = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    cd = ImageDraw.Draw(ck)
    ckr = hr * 0.30
    cd.ellipse([hx - hr * 0.62 - ckr, hy + hr * 0.28 - ckr, hx - hr * 0.62 + ckr, hy + hr * 0.28 + ckr], fill=_CHEEK)
    cd.ellipse([hx + hr * 0.64 - ckr, hy + hr * 0.30 - ckr, hx + hr * 0.64 + ckr, hy + hr * 0.30 + ckr], fill=_CHEEK)
    base = Image.alpha_composite(base, ck)
    d = ImageDraw.Draw(base)

    er, eoff, ey = hr * 0.30, hr * 0.40, hy - hr * 0.12
    for ex in (hx - eoff, hx + eoff):
        d.ellipse([ex - er, ey - er, ex + er, ey + er], fill=_WHITE)
        pr = er * 0.56
        pcx, pcy = ex + er * 0.10, ey + er * 0.08
        d.ellipse([pcx - pr, pcy - pr, pcx + pr, pcy + pr], fill=_INK)
        cr = max(1, er * 0.24)
        d.ellipse([pcx - pr * 0.5 - cr, pcy - pr * 0.5 - cr, pcx - pr * 0.5 + cr, pcy - pr * 0.5 + cr], fill=_WHITE)
    sm = hr * 0.46
    smt = ey + hr * 0.34
    d.arc([hx - sm, smt, hx + sm, smt + sm * 0.95], start=18, end=162, fill=_INK, width=max(2, int(s * 0.018)))

    spx, spy = hx + hr * 0.62, hy - hr * 1.18
    sl = s * 0.052
    sw = max(2, int(s * 0.012))
    d.line([(spx - sl, spy), (spx + sl, spy)], fill=_WHITE, width=sw)
    d.line([(spx, spy - sl), (spx, spy + sl)], fill=_WHITE, width=sw)
    d.ellipse([spx - sw, spy - sw, spx + sw, spy + sw], fill=_WHITE)
    return base


if __name__ == "__main__":
    generate_icons(force=True)
    print("icons regenerated")
