"""Generate PWA icon assets for BookWorm.

Produces PNG files inside static/img/icons/:
  icon-192.png          — standard 192×192 (rounded square)
  icon-512.png          — standard 512×512 (rounded square)
  icon-maskable-512.png — 512×512 full-bleed (Android adaptive safe-zone)
  apple-touch-icon.png  — 180×180 full-bleed square (iOS masks it itself)
  badge-96.png          — 96×96 white-on-transparent monochrome push badge

NOTE: the home-page widget *shortcut* icons (shortcut-*.png) are generated by
bw_shortcut_icons.py and are intentionally left untouched by this module.

Files are only written when missing; call generate_icons(force=True) to redraw.

Design: a cute green caterpillar — segmented body with little feet, a friendly
two-eyed face + smile, and antennae — on a fresh sky gradient. Bold and clean so
it reads from a 16 px favicon up to a 512 px home-screen icon.
"""
import os

from PIL import Image, ImageDraw, ImageFilter

# ── Palette ─────────────────────────────────────────────────────────────────
_BG_TOP   = (186, 230, 253)   # sky-200  #bae6fd
_BG_BOT   = ( 56, 189, 248)   # sky-400  #38bdf8
_GREEN    = ( 34, 163,  74)   # leaf green        #22a34a
_GREEN_HD = ( 52, 199,  89)   # brighter head     #34c759
_GREEN_HI = (134, 239, 172)   # highlight         #86efac
_GREEN_DK = ( 20,  83,  45)   # dark border/legs  #14532d
_WHITE    = (255, 255, 255)
_INK      = ( 22,  30,  24)
_CHEEK    = (244, 114, 100, 95)   # RGBA soft blush

_OUT_DIR = os.path.join(os.path.dirname(__file__), "static", "img", "icons")

# (filename, size, full_bleed) — full_bleed fills the whole square (maskable /
# apple-touch); otherwise a rounded square.
_SPECS = [
    ("icon-192.png",          192, False),
    ("icon-512.png",          512, False),
    ("icon-maskable-512.png", 512, True),
    ("apple-touch-icon.png",  180, True),
]

# Caterpillar segments as fractions of the icon size: (cx, cy, r), tail → head.
_SEGS = [
    (0.215, 0.605, 0.088),
    (0.340, 0.585, 0.104),
    (0.468, 0.560, 0.112),
    (0.595, 0.520, 0.116),
]
_HEAD = (0.730, 0.452, 0.150)   # brighter, largest


def _gradient_square(s: int, top: tuple, bottom: tuple) -> Image.Image:
    img = Image.new("RGB", (s, s))
    d = ImageDraw.Draw(img)
    for y in range(s):
        t = y / max(1, s - 1)
        d.line([(0, y), (s, y)], fill=tuple(
            int(top[i] * (1 - t) + bottom[i] * t) for i in range(3)))
    return img.convert("RGBA")


def _disc(d, cx, cy, r, fill):
    d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=fill)


def _make_icon(size: int, full_bleed: bool) -> Image.Image:
    s = size
    base = _gradient_square(s, _BG_TOP, _BG_BOT)

    if not full_bleed:
        mask = Image.new("L", (s, s), 0)
        ImageDraw.Draw(mask).rounded_rectangle(
            [0, 0, s - 1, s - 1], radius=int(s * 0.225), fill=255)
        rounded = Image.new("RGBA", (s, s), (0, 0, 0, 0))
        rounded.paste(base, (0, 0), mask)
        base = rounded

    segs = [(cx * s, cy * s, r * s) for (cx, cy, r) in _SEGS]
    hx, hy, hr = (_HEAD[0] * s, _HEAD[1] * s, _HEAD[2] * s)
    bd = max(2.0, s * 0.013)   # dark border thickness

    # ── Soft drop shadow ─────────────────────────────────────────────────────
    sh = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    sd = ImageDraw.Draw(sh)
    for (cx, cy, r) in segs + [(hx, hy, hr)]:
        sd.ellipse([cx - r, cy - r + s * 0.02, cx + r, cy + r + s * 0.02],
                   fill=(0, 0, 0, 65))
    base = Image.alpha_composite(base, sh.filter(ImageFilter.GaussianBlur(int(s * 0.02))))
    d = ImageDraw.Draw(base)

    # ── Little feet (under each body segment) ────────────────────────────────
    for (cx, cy, r) in segs:
        fy = cy + r * 0.78
        fw, fh = r * 0.30, r * 0.42
        for fx in (cx - r * 0.42, cx + r * 0.42):
            d.ellipse([fx - fw, fy - fh, fx + fw, fy + fh + r * 0.25], fill=_GREEN_DK)

    # ── Body segments: dark border, fill, highlight (tail → head) ────────────
    for (cx, cy, r) in segs:
        _disc(d, cx, cy, r + bd, _GREEN_DK)
        _disc(d, cx, cy, r, _GREEN)
    # head border + fill (brighter)
    _disc(d, hx, hy, hr + bd, _GREEN_DK)
    _disc(d, hx, hy, hr, _GREEN_HD)

    # glossy highlight crescents (top-left of each disc)
    hi = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    hd = ImageDraw.Draw(hi)
    for (cx, cy, r) in segs:
        hrr = r * 0.52
        hd.ellipse([cx - r * 0.62, cy - r * 0.66, cx - r * 0.62 + hrr, cy - r * 0.66 + hrr],
                   fill=(*_GREEN_HI, 150))
    hd.ellipse([hx - hr * 0.58, hy - hr * 0.62, hx - hr * 0.58 + hr * 0.5,
                hy - hr * 0.62 + hr * 0.5], fill=(*_GREEN_HI, 150))
    base = Image.alpha_composite(base, hi.filter(ImageFilter.GaussianBlur(int(s * 0.008))))
    d = ImageDraw.Draw(base)

    # ── Antennae ─────────────────────────────────────────────────────────────
    aw = max(2, int(s * 0.016))
    atr = max(3, int(s * 0.028))
    for sgn, lean in ((-1, 0.55), (1, 0.62)):
        bx, by = hx + sgn * hr * 0.34, hy - hr * 0.78
        tx, ty = bx + sgn * hr * 0.40, by - hr * lean
        d.line([(bx, by), (tx, ty)], fill=_GREEN_DK, width=aw)
        _disc(d, tx, ty, atr, _GREEN_HD)

    # ── Rosy cheeks ──────────────────────────────────────────────────────────
    ck = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    cd = ImageDraw.Draw(ck)
    ckr = hr * 0.26
    for sgn in (-1, 1):
        cd.ellipse([hx + sgn * hr * 0.64 - ckr, hy + hr * 0.30 - ckr,
                    hx + sgn * hr * 0.64 + ckr, hy + hr * 0.30 + ckr], fill=_CHEEK)
    base = Image.alpha_composite(base, ck)
    d = ImageDraw.Draw(base)

    # ── Eyes + smile ─────────────────────────────────────────────────────────
    er, eoff, ey = hr * 0.30, hr * 0.40, hy - hr * 0.10
    for ex in (hx - eoff, hx + eoff):
        _disc(d, ex, ey, er, _WHITE)
        pr = er * 0.56
        pcx, pcy = ex + er * 0.08, ey + er * 0.10
        _disc(d, pcx, pcy, pr, _INK)
        cr = max(1, er * 0.24)
        _disc(d, pcx - pr * 0.5, pcy - pr * 0.5, cr, _WHITE)
    sm = hr * 0.44
    smt = ey + hr * 0.34
    d.arc([hx - sm, smt, hx + sm, smt + sm * 0.95],
          start=18, end=162, fill=_INK, width=max(2, int(s * 0.017)))

    return base


def _make_badge(size: int = 96) -> Image.Image:
    """White caterpillar silhouette on transparent (Android push badge)."""
    s = size
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    for (cx, cy, r) in _SEGS:
        _disc(d, cx * s, cy * s, r * s, (255, 255, 255, 255))
    _disc(d, _HEAD[0] * s, _HEAD[1] * s, _HEAD[2] * s, (255, 255, 255, 255))
    return img


def generate_icons(out_dir: str = _OUT_DIR, force: bool = False) -> None:
    """Write PNG icons to *out_dir*. Skips existing files unless *force=True*."""
    os.makedirs(out_dir, exist_ok=True)
    for name, size, full_bleed in _SPECS:
        path = os.path.join(out_dir, name)
        if not force and os.path.exists(path):
            continue
        _make_icon(size, full_bleed).save(path, "PNG", optimize=True)
    badge_path = os.path.join(out_dir, "badge-96.png")
    if force or not os.path.exists(badge_path):
        _make_badge(96).save(badge_path, "PNG", optimize=True)


if __name__ == "__main__":
    generate_icons(force=True)
    print("icons regenerated")
